const albumsList = [
  {
    name: 'Abbey Road',
    artist: 'The Beatles',
    description: 'The iconic final album recorded by The Beatles, featuring classics like "Come Together" and "Here Comes the Sun".',
    price: 24.99,
    image: 'products/abbey-road.jpg',
    genre: 'Rock',
    releaseYear: 1969,
    trackCount: 17,
    duration: '47:23',
    stripePriceId: 'price_xxxxx_abbeyroad',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: true,
  },
  {
    name: 'Thriller',
    artist: 'Michael Jackson',
    description: 'The best-selling album of all time, featuring hits like "Billie Jean" and "Beat It".',
    price: 19.99,
    image: 'products/thriller.jpg',
    genre: 'Pop',
    releaseYear: 1982,
    trackCount: 9,
    duration: '42:19',
    stripePriceId: 'price_xxxxx_thriller',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: true,
  },
  {
    name: 'The Dark Side of the Moon',
    artist: 'Pink Floyd',
    description: 'A progressive rock masterpiece exploring themes of life, death, and human nature.',
    price: 22.99,
    image: 'products/dark-side-moon.jpg',
    genre: 'Progressive Rock',
    releaseYear: 1973,
    trackCount: 10,
    duration: '42:49',
    stripePriceId: 'price_xxxxx_darkside',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Back in Black',
    artist: 'AC/DC',
    description: 'The legendary rock album that defined AC/DC\'s sound for decades to come.',
    price: 18.99,
    image: 'products/back-in-black.jpg',
    genre: 'Hard Rock',
    releaseYear: 1980,
    trackCount: 10,
    duration: '42:11',
    stripePriceId: 'price_xxxxx_backinblack',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Rumours',
    artist: 'Fleetwood Mac',
    description: 'A masterpiece of soft rock featuring the classic lineup at their peak.',
    price: 21.99,
    image: 'products/rumours.jpg',
    genre: 'Soft Rock',
    releaseYear: 1977,
    trackCount: 11,
    duration: '39:43',
    stripePriceId: 'price_xxxxx_rumours',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Nevermind',
    artist: 'Nirvana',
    description: 'The album that defined grunge and changed the course of rock music in the 90s.',
    price: 20.99,
    image: 'products/nevermind.jpg',
    genre: 'Grunge',
    releaseYear: 1991,
    trackCount: 12,
    duration: '42:38',
    stripePriceId: 'price_xxxxx_nevermind',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: true,
  },
  {
    name: 'The Wall',
    artist: 'Pink Floyd',
    description: 'A rock opera exploring isolation and the psychological walls we build.',
    price: 29.99,
    image: 'products/the-wall.jpg',
    genre: 'Progressive Rock',
    releaseYear: 1979,
    trackCount: 26,
    duration: '81:20',
    stripePriceId: 'price_xxxxx_thewall',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Led Zeppelin IV',
    artist: 'Led Zeppelin',
    description: 'Featuring the iconic "Stairway to Heaven" and other rock classics.',
    price: 23.99,
    image: 'products/led-zeppelin-iv.jpg',
    genre: 'Hard Rock',
    releaseYear: 1971,
    trackCount: 8,
    duration: '42:34',
    stripePriceId: 'price_xxxxx_ledzeppelin4',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Hotel California',
    artist: 'Eagles',
    description: 'The definitive Eagles album with the title track and "New Kid in Town".',
    price: 19.99,
    image: 'products/hotel-california.jpg',
    genre: 'Rock',
    releaseYear: 1976,
    trackCount: 9,
    duration: '43:28',
    stripePriceId: 'price_xxxxx_hotelcalifornia',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Born to Run',
    artist: 'Bruce Springsteen',
    description: 'Springsteen\'s breakthrough album that captured the American dream.',
    price: 17.99,
    image: 'products/born-to-run.jpg',
    genre: 'Rock',
    releaseYear: 1975,
    trackCount: 8,
    duration: '39:26',
    stripePriceId: 'price_xxxxx_borntorun',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Purple Rain',
    artist: 'Prince',
    description: 'The soundtrack to the film of the same name, featuring "When Doves Cry".',
    price: 18.99,
    image: 'products/purple-rain.jpg',
    genre: 'Funk Rock',
    releaseYear: 1984,
    trackCount: 9,
    duration: '43:51',
    stripePriceId: 'price_xxxxx_purplerain',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Appetite for Destruction',
    artist: 'Guns N\' Roses',
    description: 'The debut album that brought hard rock back to the mainstream.',
    price: 21.99,
    image: 'products/appetite-destruction.jpg',
    genre: 'Hard Rock',
    releaseYear: 1987,
    trackCount: 12,
    duration: '53:51',
    stripePriceId: 'price_xxxxx_appetite',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'The Joshua Tree',
    artist: 'U2',
    description: 'U2\'s breakthrough album featuring "With or Without You" and "Where the Streets Have No Name".',
    price: 20.99,
    image: 'products/joshua-tree.jpg',
    genre: 'Rock',
    releaseYear: 1987,
    trackCount: 11,
    duration: '50:11',
    stripePriceId: 'price_xxxxx_joshuatree',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Like a Prayer',
    artist: 'Madonna',
    description: 'Madonna\'s most personal and critically acclaimed album.',
    price: 16.99,
    image: 'products/like-a-prayer.jpg',
    genre: 'Pop',
    releaseYear: 1989,
    trackCount: 11,
    duration: '50:54',
    stripePriceId: 'price_xxxxx_likeaprayer',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Bad',
    artist: 'Michael Jackson',
    description: 'The follow-up to Thriller featuring hits like "Smooth Criminal" and "Man in the Mirror".',
    price: 18.99,
    image: 'products/bad.jpg',
    genre: 'Pop',
    releaseYear: 1987,
    trackCount: 11,
    duration: '48:16',
    stripePriceId: 'price_xxxxx_bad',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'The Chronic',
    artist: 'Dr. Dre',
    description: 'The landmark album that defined West Coast hip-hop and G-funk.',
    price: 19.99,
    image: 'products/the-chronic.jpg',
    genre: 'Hip Hop',
    releaseYear: 1992,
    trackCount: 16,
    duration: '62:53',
    stripePriceId: 'price_xxxxx_chronic',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Illmatic',
    artist: 'Nas',
    description: 'Considered one of the greatest hip-hop albums ever recorded.',
    price: 17.99,
    image: 'products/illmatic.jpg',
    genre: 'Hip Hop',
    releaseYear: 1994,
    trackCount: 10,
    duration: '39:50',
    stripePriceId: 'price_xxxxx_illmatic',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'The Miseducation of Lauryn Hill',
    artist: 'Lauryn Hill',
    description: 'The groundbreaking solo debut that blended hip-hop, R&B, and soul.',
    price: 20.99,
    image: 'products/miseducation.jpg',
    genre: 'R&B',
    releaseYear: 1998,
    trackCount: 16,
    duration: '77:47',
    stripePriceId: 'price_xxxxx_miseducation',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'OK Computer',
    artist: 'Radiohead',
    description: 'The album that redefined alternative rock in the late 90s.',
    price: 22.99,
    image: 'products/ok-computer.jpg',
    genre: 'Alternative Rock',
    releaseYear: 1997,
    trackCount: 12,
    duration: '53:21',
    stripePriceId: 'price_xxxxx_okcomputer',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'In the Aeroplane Over the Sea',
    artist: 'Neutral Milk Hotel',
    description: 'Jeff Mangum\'s masterpiece of indie folk that has influenced countless artists.',
    price: 15.99,
    image: 'products/aeroplane.jpg',
    genre: 'Indie Folk',
    releaseYear: 1998,
    trackCount: 11,
    duration: '39:51',
    stripePriceId: 'price_xxxxx_aeroplane',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  }
]; 

module.exports = { albumsList }; 